### ISSUE TITLE
There's no way to disable repo adding

### ISSUE THREAD

**Issue by ares** [theforeman/ansible-foreman_scap_client#2]
In case I have repos managed externally, e.g. by using Satellite, there's no way to avoid adding repo for rubygem-foreman_scap_client as far as I can see. We should probably have some variable to enable/disable this? If the host is subscribed, we probably shouldn't add additional repo

**Comment by xprazak2** [comment]
I think we already have that, it is [foreman_scap_client_repo_state](https://github.com/theforeman/ansible-foreman_scap_client/blob/master/defaults/main.yml#L11) and [yum_repository](https://docs.ansible.com/ansible/latest/modules/yum_repository_module.html) module uses it to determine whether repo should be [enabled or not](https://github.com/theforeman/ansible-foreman_scap_client/blob/master/tasks/main.yml#L9).

**Comment by ares** [comment]
oh, got it, I was expected more of `if: ...` but this works too, thanks
