### ISSUE TITLE
ansible-galaxy versioning conflicts

### ISSUE THREAD

**Issue by PiRomant** [theforeman/ansible-foreman_scap_client#53]
```bash
ansible-galaxy install  theforeman.foreman_scap_client
```
Starting galaxy role install process
\- downloading role 'foreman_scap_client', owned by theforeman
[WARNING]: - theforeman.foreman_scap_client was NOT installed successfully:
Unable to compare role versions (0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.1.0, 0.2.0, **v0.3.0**) to determine the most recent version due to incompatible version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.

**Comment by adamruzicka** [comment]
Ah, thank you, it should be fixed now.

```
# ansible-galaxy install  theforeman.foreman_scap_client
Starting galaxy role install process
- downloading role 'foreman_scap_client', owned by theforeman
- downloading role from https://github.com/theforeman/ansible-foreman_scap_client/archive/0.3.0.tar.gz
- extracting theforeman.foreman_scap_client to /root/.ansible/roles/theforeman.foreman_scap_client
- theforeman.foreman_scap_client (0.3.0) was installed successfully
```
