### ISSUE TITLE
Ubuntu 22.04 ruby2.7

### ISSUE THREAD

**Issue by PiRomant** [theforeman/ansible-foreman_scap_client#54]
Playbook installs a ruby2.7-dependent foreman_scap_client on the Ubuntu 22.04.
```sh
# foreman_scap_client 
/usr/bin/env: ‘ruby2.7’: No such file or directory
```

**Comment by PiRomant** [comment]
Manual install from gem
```bash
gem install foreman_scap_client
```
And modifying job template, helps
![CloneJob](https://github.com/theforeman/ansible-foreman_scap_client/assets/29551044/0d9fcff6-05b6-4370-8ab4-07b88d9963fb)
![ChangeRemoteExec](https://github.com/theforeman/ansible-foreman_scap_client/assets/29551044/f2f82a5a-b3cb-4c51-acf8-b14278eb2a8c)

**Comment by adamruzicka** [comment]
> Playbook installs a ruby2.7-dependent foreman_scap_client on the Ubuntu 22.04.

That's a somewhat misleading notion. The playbook installs a package. The package comes from some repositories, but the role cannot really do anything about how dependencies are set up on the package that gets pulled. Please do raise this issue with whoever maintains the repository from which the package comes so they can properly address it.

**Comment by PiRomant** [comment]
Installation from gem is work. At least 0.5.0 version. So why is not an option to use in playbook?
