### ISSUE TITLE
Installer doesn't find rubygem-foreman_scap_client

### ISSUE THREAD

**Issue by apollo13** [theforeman/ansible-foreman_scap_client#8]
Ansible currently fails to install rubygem-foreman_scap_client because it does not enable the https://yum.theforeman.org/client/ repository but only https://yum.theforeman.org/plugins/. Is there an assumption that the client repo is already enabled? (And if yes by what)

**Comment by xprazak2** [comment]
Thank you for reporting this, [0.0.2](https://github.com/theforeman/ansible-foreman_scap_client/blob/0.0.2/defaults/main.yml#L10) was pointing to the plugins repo, which was changed in [0.0.3](https://github.com/theforeman/ansible-foreman_scap_client/blob/0.0.3/defaults/main.yml#L10). 

You also need to override the [foreman_scap_client_repo_state](https://github.com/theforeman/ansible-foreman_scap_client/blob/0.0.3/defaults/main.yml#L11) which is set to `absent` by default.

Does it resolve your issue?

**Comment by apollo13** [comment]
Ah thank you, that makes it clear and fixes it. Btw does running OpenSCAP from the host view directly requiere puppet? Is there any way to get that working with ansible?

**Comment by apollo13** [comment]
I just found https://github.com/theforeman/foreman_openscap/pull/407 -- thank you for your help!
